// Generated by Selenium IDE
package com.blackbox;

import org.junit.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import java.util.UUID;

public class UserManagement {
    private Engine engine = Engine.getInstance();
    private WebDriver driver = engine.getDriver();

    @AfterClass
    public static void tearDown(){
        Engine.getInstance().stop();
    }

    @BeforeClass
    public static void Login() throws InterruptedException {
        WebDriver driver = Engine.getInstance().getDriver();
        driver.get("http://gc21131138.imwork.net:20430/test-maker/web/admin/index.action");
        driver.findElement(By.id("username")).sendKeys("testadmin1");
        driver.findElement(By.id("password")).sendKeys("123456");
        driver.findElement(By.id("login-button")).click();
        driver.manage().window().maximize();
        Engine.getInstance().implicitlyWait();
        driver.findElement(By.linkText("用户管理")).click();
        Thread.sleep(1000);
    }

    @Test
    public void enableUser() throws InterruptedException {
        engine.refresh();
        driver.findElement(By.cssSelector("#user-data-table > tbody > tr:nth-child(4) > td:nth-child(1) > input")).click();
        driver.findElement(By.id("switch-state-btn")).click();
        driver.findElement(By.xpath("//div[3]/div/div/button[2]")).click();
        Thread.sleep(1000);
        Assert.assertEquals("操作成功！", driver.findElement(By.xpath("//div[4]/div/div/div[2]/div/div")).getText());
    }

    @Test
    public void disableUser() throws InterruptedException {
        enableUser();
    }

    @Test
    public void setAsAdmin() throws InterruptedException {
        engine.refresh();
        driver.findElement(By.cssSelector(".item-row:nth-child(4) .item-selection")).click();
        driver.findElement(By.id("switch-admin-btn")).click();
        driver.findElement(By.xpath("//div[3]/div/div/button[2]")).click();
        Thread.sleep(1000);
        Assert.assertEquals("操作成功！", driver.findElement(By.xpath("//div[4]/div/div/div[2]/div/div")).getText());
    }

    @Test
    public void cancelAdmin() throws InterruptedException {
        setAsAdmin();
    }

    @Test
    public void resetPassword() throws InterruptedException {
        engine.refresh();
        driver.findElement(By.cssSelector(".item-row:nth-child(4) .item-selection")).click();
        driver.findElement(By.id("reset-password-btn")).click();
        driver.findElement(By.xpath("//div[3]/div/div/button[2]")).click();
        Thread.sleep(1000);
        Assert.assertEquals("新密码已生成", driver.findElement(By.xpath("//div[4]/div/div/div[2]/div/div")).getText().substring(0, 6));
    }

    @Test
    public void addUserWithDifferentPassword() {
        engine.refresh();
        driver.findElement(By.cssSelector(".glyphicon-plus-sign")).click();
        driver.findElement(By.id("user-username")).sendKeys("abcd");
        driver.findElement(By.id("user-fullName")).sendKeys("ABCD");
        driver.findElement(By.id("user-phone")).sendKeys("123456");
        driver.findElement(By.id("user-email")).sendKeys("abc@xyz.com");
        driver.findElement(By.id("user-password")).sendKeys("123456");
        driver.findElement(By.id("user-password-confirm")).sendKeys("123");
        driver.findElement(By.id("submit-form-btn")).click();
        Assert.assertEquals("你的输入不相同", driver.findElement(By.id("user-password-confirm-error")).getText());
    }

    @Test
    public void addUserByFewLetterPassword() {
        engine.refresh();
        driver.findElement(By.cssSelector(".glyphicon-plus-sign")).click();
        driver.findElement(By.id("user-username")).sendKeys("abcd");
        driver.findElement(By.id("user-fullName")).sendKeys("ABCD");
        driver.findElement(By.id("user-phone")).sendKeys("123456");
        driver.findElement(By.id("user-email")).sendKeys("abc@xyz.com");
        driver.findElement(By.id("user-password")).sendKeys("123");
        driver.findElement(By.id("user-password-confirm")).sendKeys("123");
        driver.findElement(By.id("submit-form-btn")).click();
        Assert.assertEquals("最少 4 个字", driver.findElement(By.id("user-password-error")).getText());
    }

    @Test
    public void addUserWithFewLetterUsername() {
        engine.refresh();
        driver.findElement(By.cssSelector(".glyphicon-plus-sign")).click();
        driver.findElement(By.id("user-username")).sendKeys("abc");
        driver.findElement(By.id("user-fullName")).sendKeys("ABCD");
        driver.findElement(By.id("user-phone")).sendKeys("123456");
        driver.findElement(By.id("user-email")).sendKeys("abc@xyz.com");
        driver.findElement(By.id("user-password")).sendKeys("123456");
        driver.findElement(By.id("user-password-confirm")).sendKeys("123456");
        driver.findElement(By.id("submit-form-btn")).click();
        Assert.assertEquals("最少 4 个字", driver.findElement(By.id("user-username-error")).getText());
    }

    @Test
    public void addUserWithInvalidEmail() {
        engine.refresh();
        driver.findElement(By.cssSelector(".glyphicon-plus-sign")).click();
        driver.findElement(By.id("user-username")).sendKeys("abcd");
        driver.findElement(By.id("user-fullName")).sendKeys("ABCD");
        driver.findElement(By.id("user-phone")).sendKeys("123456");
        driver.findElement(By.id("user-email")).sendKeys("abc@");
        driver.findElement(By.id("user-password")).sendKeys("123456");
        driver.findElement(By.id("user-password-confirm")).sendKeys("123456");
        driver.findElement(By.id("submit-form-btn")).click();
        Assert.assertEquals("请输入有效的电子邮件", driver.findElement(By.id("user-email-error")).getText());
    }

    @Test
    public void addUser() throws InterruptedException {
        engine.refresh();
        String username = UUID.randomUUID().toString().substring(0, 8);

        driver.findElement(By.cssSelector(".glyphicon-plus-sign")).click();
        driver.findElement(By.id("user-username")).sendKeys(username);
        driver.findElement(By.id("user-fullName")).sendKeys(username);
        driver.findElement(By.id("user-phone")).sendKeys("123456");
        driver.findElement(By.id("user-email")).sendKeys("abc@xyz.com");
        driver.findElement(By.id("user-password")).sendKeys("123456");
        driver.findElement(By.id("user-password-confirm")).sendKeys("123456");
        driver.findElement(By.id("submit-form-btn")).click();
        Thread.sleep(1000);
        Assert.assertEquals("操作成功！", driver.findElement(By.xpath("//div[4]/div/div/div[2]/div/div")).getText());
    }
}
