// Generated by Selenium IDE
package com.mrsongshu;

import org.junit.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class EnableUser {
    private Engine engine = Engine.getInstance();
    private WebDriver driver = engine.getDriver();
    private WebDriverWait wait = engine.getWait();

    @AfterClass
    public static void tearDown(){
        Engine.getInstance().stop();
    }

    @Before
    public void Login() {
        driver.get("http://gc21131138.imwork.net:20430/test-maker/web/admin/index.action");
        driver.manage().window().setSize(new Dimension(1280, 800));
        driver.findElement(By.id("username")).sendKeys("testadmin1");
        driver.findElement(By.id("password")).sendKeys("123456");
        driver.findElement(By.id("login-button")).click();
        driver.manage().window().maximize();
    }

    @Test
    public void enableUser(){
        engine.implicitlyWait();
        driver.findElement(By.linkText("用户管理")).click();
        driver.findElement(By.cssSelector("#user-data-table > tbody > tr:nth-child(4) > td:nth-child(1) > input")).click();
        driver.findElement(By.id("switch-state-btn")).click();
        driver.findElement(By.xpath("//div[3]/div/div/button[2]")).click();
    }

    @Test
    public void disableUser(){
        engine.implicitlyWait();
        driver.findElement(By.linkText("用户管理")).click();
        driver.findElement(By.cssSelector("#user-data-table > tbody > tr:nth-child(4) > td:nth-child(1) > input")).click();
        driver.findElement(By.id("switch-state-btn")).click();
        driver.findElement(By.xpath("//div[3]/div/div/button[2]")).click();
    }
}
