// Generated by Selenium IDE
package com.mrsongshu;

import org.junit.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;

public class UserManagement {
    private Engine engine = Engine.getInstance();
    private WebDriver driver = engine.getDriver();

    @AfterClass
    public static void tearDown(){
        Engine.getInstance().stop();
    }

    @Before
    public void Login() {
        driver.get("http://gc21131138.imwork.net:20430/test-maker/web/admin/index.action");
        driver.manage().window().setSize(new Dimension(1280, 800));
        driver.findElement(By.id("username")).sendKeys("testadmin1");
        driver.findElement(By.id("password")).sendKeys("123456");
        driver.findElement(By.id("login-button")).click();
        driver.manage().window().maximize();
    }

    @Test
    public void enableUser() throws InterruptedException {
        engine.implicitlyWait();
        driver.findElement(By.linkText("用户管理")).click();
        driver.findElement(By.cssSelector("#user-data-table > tbody > tr:nth-child(4) > td:nth-child(1) > input")).click();
        driver.findElement(By.id("switch-state-btn")).click();
        driver.findElement(By.xpath("//div[3]/div/div/button[2]")).click();
        Thread.sleep(1000);
        Assert.assertEquals(driver.findElement(By.xpath("//div[4]/div/div/div[2]/div/div")).getText(), "操作成功！");
    }

    @Test
    public void disableUser() throws InterruptedException {
        enableUser();
    }

    @Test
    public void setAsAdmin() throws InterruptedException {
        engine.implicitlyWait();
        driver.findElement(By.linkText("用户管理")).click();
        driver.findElement(By.cssSelector(".item-row:nth-child(4) .item-selection")).click();
        driver.findElement(By.id("switch-admin-btn")).click();
        driver.findElement(By.xpath("//div[3]/div/div/button[2]")).click();
        Thread.sleep(1000);
        Assert.assertEquals(driver.findElement(By.xpath("//div[4]/div/div/div[2]/div/div")).getText(), "操作成功！");
    }

    @Test
    public void cancelAdmin() throws InterruptedException {
        setAsAdmin();
    }

    @Test
    public void resetPassword() throws InterruptedException {
        engine.implicitlyWait();
        driver.findElement(By.linkText("用户管理")).click();
        driver.findElement(By.cssSelector(".item-row:nth-child(4) .item-selection")).click();
        driver.findElement(By.id("reset-password-btn")).click();
        driver.findElement(By.xpath("//div[3]/div/div/button[2]")).click();
        Thread.sleep(1000);
        Assert.assertEquals(driver.findElement(By.xpath("//div[4]/div/div/div[2]/div/div")).getText().substring(0, 6), "新密码已生成");
    }

    @Test
    public void addUserWithDifferentPassword() {
        engine.implicitlyWait();
        driver.findElement(By.linkText("用户管理")).click();
        driver.findElement(By.cssSelector(".glyphicon-plus-sign")).click();
        driver.findElement(By.id("user-username")).sendKeys("abcd");
        driver.findElement(By.id("user-fullName")).sendKeys("ABCD");
        driver.findElement(By.id("user-phone")).sendKeys("123456");
        driver.findElement(By.id("user-email")).sendKeys("abc@xyz.com");
        driver.findElement(By.id("user-password")).sendKeys("123456");
        driver.findElement(By.id("user-password-confirm")).sendKeys("123");
        driver.findElement(By.id("submit-form-btn")).click();
        Assert.assertEquals(driver.findElement(By.id("user-password-confirm-error")).getText(), "你的输入不相同");
    }

    @Test
    public void addUserByFewLetterPassword() {
        engine.implicitlyWait();
        driver.findElement(By.linkText("用户管理")).click();
        driver.findElement(By.cssSelector(".glyphicon-plus-sign")).click();
        driver.findElement(By.id("user-username")).sendKeys("abcd");
        driver.findElement(By.id("user-fullName")).sendKeys("ABCD");
        driver.findElement(By.id("user-phone")).sendKeys("123456");
        driver.findElement(By.id("user-email")).sendKeys("abc@xyz.com");
        driver.findElement(By.id("user-password")).sendKeys("123");
        driver.findElement(By.id("user-password-confirm")).sendKeys("123");
        driver.findElement(By.id("submit-form-btn")).click();
        Assert.assertEquals(driver.findElement(By.id("user-password-error")).getText(), "最少 4 个字");
    }
}
